# Generated by Django 2.2.3 on 2019-07-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='cpassword',
            field=models.CharField(default='GKt15sdgn@6', max_length=128),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='password',
            field=models.CharField(default='GKt15sdgn@6', max_length=128),
        ),
    ]
